// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'account_move_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AccountMoveModel _$AccountMoveModelFromJson(Map<String, dynamic> json) =>
    AccountMoveModel(
      name: json['name'],
      date: json['date'],
      ref: json['ref'],
      narration: json['narration'],
      state: json['state'],
      type: json['type'],
      typeName: json['type_name'],
      toCheck: json['to_check'],
      journalId: json['journal_id'],
      companyId: json['company_id'],
      companyCurrencyId: json['company_currency_id'],
      currencyId: json['currency_id'],
      lineIds: json['line_ids'],
      partnerId: json['partner_id'],
      commercialPartnerId: json['commercial_partner_id'],
      amountUntaxed: json['amount_untaxed'],
      amountTax: json['amount_tax'],
      amountTotal: json['amount_total'],
      amountResidual: json['amount_residual'],
      amountUntaxedSigned: json['amount_untaxed_signed'],
      amountTaxSigned: json['amount_tax_signed'],
      amountTotalSigned: json['amount_total_signed'],
      amountResidualSigned: json['amount_residual_signed'],
      amountByGroup: json['amount_by_group'],
      taxCashBasisRecId: json['tax_cash_basis_rec_id'],
      autoPost: json['auto_post'],
      reversedEntryId: json['reversed_entry_id'],
      reversalMoveId: json['reversal_move_id'],
      fiscalPositionId: json['fiscal_position_id'],
      invoiceUserId: json['invoice_user_id'],
      userId: json['user_id'],
      invoicePaymentState: json['invoice_payment_state'],
      invoiceDate: json['invoice_date'],
      invoiceDateDue: json['invoice_date_due'],
      invoicePaymentRef: json['invoice_payment_ref'],
      invoiceSent: json['invoice_sent'],
      invoiceOrigin: json['invoice_origin'],
      invoicePaymentTermId: json['invoice_payment_term_id'],
      invoiceLineIds: json['invoice_line_ids'],
      invoicePartnerBankId: json['invoice_partner_bank_id'],
      invoiceIncotermId: json['invoice_incoterm_id'],
      invoiceOutstandingCreditsDebitsWidget:
          json['invoice_outstanding_credits_debits_widget'],
      invoicePaymentsWidget: json['invoice_payments_widget'],
      invoiceHasOutstanding: json['invoice_has_outstanding'],
      invoiceVendorBillId: json['invoice_vendor_bill_id'],
      invoiceSourceEmail: json['invoice_source_email'],
      invoicePartnerDisplayName: json['invoice_partner_display_name'],
      invoicePartnerIcon: json['invoice_partner_icon'],
      invoiceCashRoundingId: json['invoice_cash_rounding_id'],
      invoiceSequenceNumberNext: json['invoice_sequence_number_next'],
      invoiceSequenceNumberNextPrefix:
          json['invoice_sequence_number_next_prefix'],
      invoiceFilterTypeDomain: json['invoice_filter_type_domain'],
      bankPartnerId: json['bank_partner_id'],
      invoiceHasMatchingSuspenseAmount:
          json['invoice_has_matching_suspense_amount'],
      taxLockDateMessage: json['tax_lock_date_message'],
      hasReconciledEntries: json['has_reconciled_entries'],
      restrictModeHashTable: json['restrict_mode_hash_table'],
      secureSequenceNumber: json['secure_sequence_number'],
      inalterableHash: json['inalterable_hash'],
      stringToHash: json['string_to_hash'],
      transactionIds: json['transaction_ids'],
      authorizedTransactionIds: json['authorized_transaction_ids'],
      purchaseVendorBillId: json['purchase_vendor_bill_id'],
      purchaseId: json['purchase_id'],
      stockMoveId: json['stock_move_id'],
      stockValuationLayerIds: json['stock_valuation_layer_ids'],
      posOrderIds: json['pos_order_ids'],
      teamId: json['team_id'],
      partnerShippingId: json['partner_shipping_id'],
      timesheetIds: json['timesheet_ids'],
      timesheetCount: json['timesheet_count'],
      campaignId: json['campaign_id'],
      sourceId: json['source_id'],
      mediumId: json['medium_id'],
      activityIds: json['activity_ids'],
      activityState: json['activity_state'],
      activityUserId: json['activity_user_id'],
      activityTypeId: json['activity_type_id'],
      activityDateDeadline: json['activity_date_deadline'],
      activitySummary: json['activity_summary'],
      activityExceptionDecoration: json['activity_exception_decoration'],
      activityExceptionIcon: json['activity_exception_icon'],
      messageIsFollower: json['message_is_follower'],
      messageFollowerIds: json['message_follower_ids'],
      messagePartnerIds: json['message_partner_ids'],
      messageChannelIds: json['message_channel_ids'],
      messageIds: json['message_ids'],
      messageUnread: json['message_unread'],
      messageUnreadCounter: json['message_unread_counter'],
      messageNeedaction: json['message_needaction'],
      messageNeedactionCounter: json['message_needaction_counter'],
      messageHasError: json['message_has_error'],
      messageHasErrorCounter: json['message_has_error_counter'],
      messageAttachmentCount: json['message_attachment_count'],
      messageMainAttachmentId: json['message_main_attachment_id'],
      websiteMessageIds: json['website_message_ids'],
      messageHasSmsError: json['message_has_sms_error'],
      accessUrl: json['access_url'],
      accessToken: json['access_token'],
      accessWarning: json['access_warning'],
      id: json['id'],
      displayName: json['display_name'],
      createUid: json['create_uid'],
      createDate: json['create_date'],
      writeUid: json['write_uid'],
      writeDate: json['write_date'],
      lastUpdate: json['__last_update'],
      statusInPayment: json['status_in_payment'],
      amountTotalInCurrencySigned: json['amount_total_in_currency_signed'],
    );

Map<String, dynamic> _$AccountMoveModelToJson(AccountMoveModel instance) =>
    <String, dynamic>{
      'name': instance.name,
      'date': instance.date,
      'ref': instance.ref,
      'narration': instance.narration,
      'state': instance.state,
      'type': instance.type,
      'type_name': instance.typeName,
      'to_check': instance.toCheck,
      'journal_id': instance.journalId,
      'company_id': instance.companyId,
      'company_currency_id': instance.companyCurrencyId,
      'currency_id': instance.currencyId,
      'line_ids': instance.lineIds,
      'partner_id': instance.partnerId,
      'commercial_partner_id': instance.commercialPartnerId,
      'amount_untaxed': instance.amountUntaxed,
      'amount_tax': instance.amountTax,
      'amount_total': instance.amountTotal,
      'amount_residual': instance.amountResidual,
      'amount_untaxed_signed': instance.amountUntaxedSigned,
      'amount_tax_signed': instance.amountTaxSigned,
      'amount_total_signed': instance.amountTotalSigned,
      'amount_residual_signed': instance.amountResidualSigned,
      'amount_by_group': instance.amountByGroup,
      'tax_cash_basis_rec_id': instance.taxCashBasisRecId,
      'auto_post': instance.autoPost,
      'reversed_entry_id': instance.reversedEntryId,
      'reversal_move_id': instance.reversalMoveId,
      'fiscal_position_id': instance.fiscalPositionId,
      'invoice_user_id': instance.invoiceUserId,
      'user_id': instance.userId,
      'invoice_payment_state': instance.invoicePaymentState,
      'invoice_date': instance.invoiceDate,
      'invoice_date_due': instance.invoiceDateDue,
      'invoice_payment_ref': instance.invoicePaymentRef,
      'invoice_sent': instance.invoiceSent,
      'invoice_origin': instance.invoiceOrigin,
      'invoice_payment_term_id': instance.invoicePaymentTermId,
      'invoice_line_ids': instance.invoiceLineIds,
      'invoice_partner_bank_id': instance.invoicePartnerBankId,
      'invoice_incoterm_id': instance.invoiceIncotermId,
      'invoice_outstanding_credits_debits_widget':
          instance.invoiceOutstandingCreditsDebitsWidget,
      'invoice_payments_widget': instance.invoicePaymentsWidget,
      'invoice_has_outstanding': instance.invoiceHasOutstanding,
      'invoice_vendor_bill_id': instance.invoiceVendorBillId,
      'invoice_source_email': instance.invoiceSourceEmail,
      'invoice_partner_display_name': instance.invoicePartnerDisplayName,
      'invoice_partner_icon': instance.invoicePartnerIcon,
      'invoice_cash_rounding_id': instance.invoiceCashRoundingId,
      'invoice_sequence_number_next': instance.invoiceSequenceNumberNext,
      'invoice_sequence_number_next_prefix':
          instance.invoiceSequenceNumberNextPrefix,
      'invoice_filter_type_domain': instance.invoiceFilterTypeDomain,
      'bank_partner_id': instance.bankPartnerId,
      'invoice_has_matching_suspense_amount':
          instance.invoiceHasMatchingSuspenseAmount,
      'tax_lock_date_message': instance.taxLockDateMessage,
      'has_reconciled_entries': instance.hasReconciledEntries,
      'restrict_mode_hash_table': instance.restrictModeHashTable,
      'secure_sequence_number': instance.secureSequenceNumber,
      'inalterable_hash': instance.inalterableHash,
      'string_to_hash': instance.stringToHash,
      'transaction_ids': instance.transactionIds,
      'authorized_transaction_ids': instance.authorizedTransactionIds,
      'purchase_vendor_bill_id': instance.purchaseVendorBillId,
      'purchase_id': instance.purchaseId,
      'stock_move_id': instance.stockMoveId,
      'stock_valuation_layer_ids': instance.stockValuationLayerIds,
      'pos_order_ids': instance.posOrderIds,
      'team_id': instance.teamId,
      'partner_shipping_id': instance.partnerShippingId,
      'timesheet_ids': instance.timesheetIds,
      'timesheet_count': instance.timesheetCount,
      'campaign_id': instance.campaignId,
      'source_id': instance.sourceId,
      'medium_id': instance.mediumId,
      'activity_ids': instance.activityIds,
      'activity_state': instance.activityState,
      'activity_user_id': instance.activityUserId,
      'activity_type_id': instance.activityTypeId,
      'activity_date_deadline': instance.activityDateDeadline,
      'activity_summary': instance.activitySummary,
      'activity_exception_decoration': instance.activityExceptionDecoration,
      'activity_exception_icon': instance.activityExceptionIcon,
      'message_is_follower': instance.messageIsFollower,
      'message_follower_ids': instance.messageFollowerIds,
      'message_partner_ids': instance.messagePartnerIds,
      'message_channel_ids': instance.messageChannelIds,
      'message_ids': instance.messageIds,
      'message_unread': instance.messageUnread,
      'message_unread_counter': instance.messageUnreadCounter,
      'message_needaction': instance.messageNeedaction,
      'message_needaction_counter': instance.messageNeedactionCounter,
      'message_has_error': instance.messageHasError,
      'message_has_error_counter': instance.messageHasErrorCounter,
      'message_attachment_count': instance.messageAttachmentCount,
      'message_main_attachment_id': instance.messageMainAttachmentId,
      'website_message_ids': instance.websiteMessageIds,
      'message_has_sms_error': instance.messageHasSmsError,
      'access_url': instance.accessUrl,
      'access_token': instance.accessToken,
      'access_warning': instance.accessWarning,
      'id': instance.id,
      'display_name': instance.displayName,
      'create_uid': instance.createUid,
      'create_date': instance.createDate,
      'write_uid': instance.writeUid,
      'write_date': instance.writeDate,
      '__last_update': instance.lastUpdate,
      'status_in_payment': instance.statusInPayment,
      'amount_total_in_currency_signed': instance.amountTotalInCurrencySigned,
    };

SalesAdvancePaymentInvoice _$SalesAdvancePaymentInvoiceFromJson(
        Map<String, dynamic> json) =>
    SalesAdvancePaymentInvoice(
      id: json['id'] as int?,
      count: json['count'],
      advancePaymentMethod: json['advance_payment_method'],
      hasDownPayments: json['has_down_payments'],
      deductDownPayments: json['deduct_down_payments'],
      productId: json['product_id'],
      currencyId: json['currency_id'],
      fixedAmount: json['fixed_amount'],
      amount: json['amount'],
      depositAccountId: json['deposit_account_id'],
      depositTaxesId: json['deposit_taxes_id'],
      displayName: json['display_name'],
    );

Map<String, dynamic> _$SalesAdvancePaymentInvoiceToJson(
        SalesAdvancePaymentInvoice instance) =>
    <String, dynamic>{
      'id': instance.id,
      'count': instance.count,
      'advance_payment_method': instance.advancePaymentMethod,
      'has_down_payments': instance.hasDownPayments,
      'deduct_down_payments': instance.deductDownPayments,
      'product_id': instance.productId,
      'currency_id': instance.currencyId,
      'fixed_amount': instance.fixedAmount,
      'amount': instance.amount,
      'deposit_account_id': instance.depositAccountId,
      'deposit_taxes_id': instance.depositTaxesId,
      'display_name': instance.displayName,
    };
