name: gsolution
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  device_info_plus: ^11.2.0
  dio: ^5.7.0
  shared_preferences: ^2.3.4
  get: ^4.6.6
  logger: ^2.5.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  country_code_picker: ^3.1.0
  cached_network_image: ^3.4.1
  flutter_form_builder: ^9.6.0
  google_fonts: ^6.2.1
  json_serializable: ^6.9.0
  mobile_scanner: ^6.0.2
  image_picker: ^1.1.2
  grouped_list: ^6.0.0
  form_builder_image_picker: ^4.1.0
  flutter_onboarding_slider: ^1.0.11
  flutter_svg: ^2.0.16
  carousel_slider: ^5.0.0
  fl_chart: ^0.70.0
  sidebarx: ^0.17.1
  cherry_toast: ^1.11.0
  flutter_rounded_date_picker: ^3.0.4
  card_slider: ^1.0.5
  expansion_tile_card: ^3.0.0
  flutter_easy_faq: ^1.0.1
  pdf: ^3.11.1
  printing: ^5.13.4
  path_provider: ^2.1.5
  win32: ^5.9.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  form_builder_validators: ^11.1.1
  floating_action_bubble: ^1.1.4
  dropdown_search: ^6.0.1
  syncfusion_flutter_pdfviewer: ^28.1.38
  htmltopdfwidgets: ^1.0.6
  webview_flutter: ^4.10.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.7
  open_file: ^3.5.10
  font_awesome_flutter: ^10.8.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  
dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoBlack
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
    - family: RobotoBlackItalic
      fonts:
        - asset: assets/fonts/Roboto-BlackItalic.ttf
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoBoldItalic
      fonts:
        - asset: assets/fonts/Roboto-BoldItalic.ttf
    - family: RobotoItalic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: RobotoLightItalic
      fonts:
        - asset: assets/fonts/Roboto-LightItalic.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoMediumItalic
      fonts:
        - asset: assets/fonts/Roboto-MediumItalic.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
    - family: RobotoThinItalic
      fonts:
        - asset: assets/fonts/Roboto-ThinItalic.ttf

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/logo/
    - assets/icons/icon_image/
    - assets/images/avatar/
    - assets/icons/icon_svg/
    - assets/images/offer/
    - assets/images/products/
    - assets/images/other/
    - assets/images/logo/icon.png
    - assets/images/offer/banner.png
