// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'stock_move_line_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

StockMoveLineModel _$StockMoveLineModelFromJson(Map<String, dynamic> json) =>
    StockMoveLineModel(
      pickingId: json['picking_id'],
      moveId: json['move_id'],
      companyId: json['company_id'],
      productId: json['product_id'],
      productUomId: json['product_uom_id'],
      productQty: json['product_qty'],
      productUomQty: json['product_uom_qty'],
      qtyDone: json['qty_done'],
      packageId: json['package_id'],
      packageLevelId: json['package_level_id'],
      lotId: json['lot_id'],
      lotName: json['lot_name'],
      resultPackageId: json['result_package_id'],
      date: json['date'],
      ownerId: json['owner_id'],
      locationId: json['location_id'],
      locationDestId: json['location_dest_id'],
      lotsVisible: json['lots_visible'],
      pickingCode: json['picking_code'],
      pickingTypeUseCreateLots: json['picking_type_use_create_lots'],
      pickingTypeUseExistingLots: json['picking_type_use_existing_lots'],
      state: json['state'],
      isInitialDemandEditable: json['is_initial_demand_editable'],
      isLocked: json['is_locked'],
      consumeLineIds: json['consume_line_ids'],
      produceLineIds: json['produce_line_ids'],
      reference: json['reference'],
      tracking: json['tracking'],
      origin: json['origin'],
      pickingTypeEntirePacks: json['picking_type_entire_packs'],
      descriptionPicking: json['description_picking'],
      id: json['id'],
      displayName: json['display_name'],
      createUid: json['create_uid'],
      createDate: json['create_date'],
      writeUid: json['write_uid'],
      writeDate: json['write_date'],
      lLastUpdate: json['__last_update'],
    );

Map<String, dynamic> _$StockMoveLineModelToJson(StockMoveLineModel instance) =>
    <String, dynamic>{
      'picking_id': instance.pickingId,
      'move_id': instance.moveId,
      'company_id': instance.companyId,
      'product_id': instance.productId,
      'product_uom_id': instance.productUomId,
      'product_qty': instance.productQty,
      'product_uom_qty': instance.productUomQty,
      'qty_done': instance.qtyDone,
      'package_id': instance.packageId,
      'package_level_id': instance.packageLevelId,
      'lot_id': instance.lotId,
      'lot_name': instance.lotName,
      'result_package_id': instance.resultPackageId,
      'date': instance.date,
      'owner_id': instance.ownerId,
      'location_id': instance.locationId,
      'location_dest_id': instance.locationDestId,
      'lots_visible': instance.lotsVisible,
      'picking_code': instance.pickingCode,
      'picking_type_use_create_lots': instance.pickingTypeUseCreateLots,
      'picking_type_use_existing_lots': instance.pickingTypeUseExistingLots,
      'state': instance.state,
      'is_initial_demand_editable': instance.isInitialDemandEditable,
      'is_locked': instance.isLocked,
      'consume_line_ids': instance.consumeLineIds,
      'produce_line_ids': instance.produceLineIds,
      'reference': instance.reference,
      'tracking': instance.tracking,
      'origin': instance.origin,
      'picking_type_entire_packs': instance.pickingTypeEntirePacks,
      'description_picking': instance.descriptionPicking,
      'id': instance.id,
      'display_name': instance.displayName,
      'create_uid': instance.createUid,
      'create_date': instance.createDate,
      'write_uid': instance.writeUid,
      'write_date': instance.writeDate,
      '__last_update': instance.lLastUpdate,
    };
