// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'order_line_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OrderLineModel _$OrderLineModelFromJson(Map<String, dynamic> json) =>
    OrderLineModel(
      id: json['id'],
      sequence: json['sequence'],
      displayType: json['display_type'],
      productUomCategoryId: json['product_uom_category_id'],
      productUpdatable: json['product_updatable'],
      productId: json['product_id'],
      productTemplateId: json['product_template_id'],
      name: json['name'],
      analyticTagIds: json['analytic_tag_ids'],
      routeId: json['route_id'],
      productUomQty: json['product_uom_qty'],
      productType: json['product_type'],
      virtualAvailableAtDate: json['virtual_available_at_date'],
      qtyAvailableToday: json['qty_available_today'],
      freeQtyToday: json['free_qty_today'],
      scheduledDate: json['scheduled_date'],
      warehouseId: json['warehouse_id'],
      qtyToDeliver: json['qty_to_deliver'],
      isMto: json['is_mto'],
      displayQtyWidget: json['display_qty_widget'],
      qtyDelivered: json['qty_delivered'],
      qtyDeliveredManual: json['qty_delivered_manual'],
      qtyDeliveredMethod: json['qty_delivered_method'],
      qtyInvoiced: json['qty_invoiced'],
      qtyToInvoice: json['qty_to_invoice'],
      productUom: json['product_uom'],
      customerLead: json['customer_lead'],
      productPackaging: json['product_packaging'],
      priceUnit: json['price_unit'],
      taxId: json['tax_id'],
      discount: json['discount'],
      priceSubtotal: json['price_subtotal'],
      priceTotal: json['price_total'],
      state: json['state'],
      invoiceStatus: json['invoice_status'],
      currencyId: json['currency_id'],
      priceTax: json['price_tax'],
      companyId: json['company_id'],
    );

Map<String, dynamic> _$OrderLineModelToJson(OrderLineModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'sequence': instance.sequence,
      'display_type': instance.displayType,
      'product_uom_category_id': instance.productUomCategoryId,
      'product_updatable': instance.productUpdatable,
      'product_id': instance.productId,
      'product_template_id': instance.productTemplateId,
      'name': instance.name,
      'analytic_tag_ids': instance.analyticTagIds,
      'route_id': instance.routeId,
      'product_uom_qty': instance.productUomQty,
      'product_type': instance.productType,
      'virtual_available_at_date': instance.virtualAvailableAtDate,
      'qty_available_today': instance.qtyAvailableToday,
      'free_qty_today': instance.freeQtyToday,
      'scheduled_date': instance.scheduledDate,
      'warehouse_id': instance.warehouseId,
      'qty_to_deliver': instance.qtyToDeliver,
      'is_mto': instance.isMto,
      'display_qty_widget': instance.displayQtyWidget,
      'qty_delivered': instance.qtyDelivered,
      'qty_delivered_manual': instance.qtyDeliveredManual,
      'qty_delivered_method': instance.qtyDeliveredMethod,
      'qty_invoiced': instance.qtyInvoiced,
      'qty_to_invoice': instance.qtyToInvoice,
      'product_uom': instance.productUom,
      'customer_lead': instance.customerLead,
      'product_packaging': instance.productPackaging,
      'price_unit': instance.priceUnit,
      'tax_id': instance.taxId,
      'discount': instance.discount,
      'price_subtotal': instance.priceSubtotal,
      'price_total': instance.priceTotal,
      'state': instance.state,
      'invoice_status': instance.invoiceStatus,
      'currency_id': instance.currencyId,
      'price_tax': instance.priceTax,
      'company_id': instance.companyId,
    };
