// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'account_journal_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AccountJournalModel _$AccountJournalModelFromJson(Map<String, dynamic> json) =>
    AccountJournalModel(
      id: json['id'],
      name: json['name'],
      active: json['active'],
      type: json['type'],
      companyId: json['company_id'],
      companyPartnerId: json['company_partner_id'],
      bankAccountId: json['bank_account_id'],
      bankId: json['bank_id'],
      bankStatementsSource: json['bank_statements_source'],
      code: json['code'],
      sequence_number_next: json['sequence_number_next'],
      sequence_id: json['sequence_id'],
      refund_sequence: json['refund_sequence'],
      refund_sequence_number_next: json['refund_sequence_number_next'],
      refund_sequence_id: json['refund_sequence_id'],
      default_debit_account_id: json['default_debit_account_id'],
      default_credit_account_id: json['default_credit_account_id'],
      currency_id: json['currency_id'],
      invoice_reference_type: json['invoice_reference_type'],
      invoice_reference_model: json['invoice_reference_model'],
      alias_id: json['alias_id'],
      alias_name: json['alias_name'],
      alias_domain: json['alias_domain'],
      profit_account_id: json['profit_account_id'],
      loss_account_id: json['loss_account_id'],
      post_at: json['post_at'],
      type_control_ids: json['type_control_ids'],
      account_control_ids: json['account_control_ids'],
      restrict_mode_hash_table: json['restrict_mode_hash_table'],
      inboundPaymentMethodLineIds: json['inbound_payment_method_line_ids'],
      outboundPaymentMethodLineIds: json['outbound_payment_method_line_ids'],
      message_follower_ids: json['message_follower_ids'],
      activity_ids: json['activity_ids'],
      message_ids: json['message_ids'],
      message_attachment_count: json['message_attachment_count'],
      displayName: json['display_name'],
      defaultAccountId: json['default_account_id'],
    );

Map<String, dynamic> _$AccountJournalModelToJson(
        AccountJournalModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'active': instance.active,
      'type': instance.type,
      'company_id': instance.companyId,
      'company_partner_id': instance.companyPartnerId,
      'bank_account_id': instance.bankAccountId,
      'bank_id': instance.bankId,
      'bank_statements_source': instance.bankStatementsSource,
      'code': instance.code,
      'sequence_number_next': instance.sequence_number_next,
      'sequence_id': instance.sequence_id,
      'refund_sequence': instance.refund_sequence,
      'refund_sequence_number_next': instance.refund_sequence_number_next,
      'refund_sequence_id': instance.refund_sequence_id,
      'default_debit_account_id': instance.default_debit_account_id,
      'default_credit_account_id': instance.default_credit_account_id,
      'currency_id': instance.currency_id,
      'invoice_reference_type': instance.invoice_reference_type,
      'invoice_reference_model': instance.invoice_reference_model,
      'alias_id': instance.alias_id,
      'alias_name': instance.alias_name,
      'alias_domain': instance.alias_domain,
      'profit_account_id': instance.profit_account_id,
      'loss_account_id': instance.loss_account_id,
      'post_at': instance.post_at,
      'type_control_ids': instance.type_control_ids,
      'account_control_ids': instance.account_control_ids,
      'restrict_mode_hash_table': instance.restrict_mode_hash_table,
      'inbound_payment_method_line_ids': instance.inboundPaymentMethodLineIds,
      'outbound_payment_method_line_ids': instance.outboundPaymentMethodLineIds,
      'message_follower_ids': instance.message_follower_ids,
      'activity_ids': instance.activity_ids,
      'message_ids': instance.message_ids,
      'message_attachment_count': instance.message_attachment_count,
      'display_name': instance.displayName,
      'default_account_id': instance.defaultAccountId,
    };
